# Generated by Django 5.2.16 on 2026-07-17 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('is_critical_asset', models.BooleanField(default=False, help_text='Downtime is tracked only for critical assets (MRI, CT, ...)')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('working', 'Working'), ('in_repair', 'In Repair'), ('condemned', 'Condemned')], default='working', max_length=20)),
                ('condemned_at', models.DateTimeField(blank=True, null=True)),
                ('condemned_location', models.CharField(blank=True, max_length=200)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.department')),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['name', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('working', 'Working'), ('in_repair', 'In Repair'), ('condemned', 'Condemned')], max_length=20)),
                ('new_status', models.CharField(choices=[('working', 'Working'), ('in_repair', 'In Repair'), ('condemned', 'Condemned')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='equipment.equipment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
