# Generated by Django 5.2.16 on 2026-07-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_statusevent_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='model_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
