# Generated by Django 5.2.16 on 2026-07-17 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('repair_started_at', models.DateTimeField(blank=True, null=True)),
                ('repair_completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('repaired', 'Repaired'), ('condemned', 'Condemned')], max_length=20, null=True)),
                ('fault_category', models.CharField(blank=True, choices=[('electrical', 'Electrical'), ('battery_power', 'Battery / Power'), ('display_monitor', 'Display / Monitor'), ('mechanical', 'Mechanical'), ('calibration', 'Calibration'), ('software', 'Software'), ('accessory_probe', 'Accessory / Probe'), ('other', 'Other')], help_text='Required when completing a repair.', max_length=30, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorders_closed', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='equipment.equipment')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workorders_opened', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, help_text='Engineers who worked on this repair.', related_name='workorders_participated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('note', 'Note'), ('delay', 'Delay'), ('system', 'System')], default='note', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remarks', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remarks', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('attached', 'Attached to Work Order'), ('closed', 'Closed')], default='open', max_length=20)),
                ('close_reason', models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('duplicate', 'Duplicate'), ('no_fault', 'No Fault Found')], max_length=20, null=True)),
                ('close_note', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints_closed', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='duplicates', to='maintenance.complaint')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='equipment.equipment')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints_reported', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['completed', 'cancelled']), _negated=True), fields=('equipment',), name='one_active_workorder_per_equipment'),
        ),
    ]
