# Generated by Django 5.2.16 on 2026-07-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='functional_confirmation',
            field=models.CharField(blank=True, choices=[('functional', 'Functional'), ('not_functional', 'Not functional')], max_length=20, null=True),
        ),
    ]
