# Generated by Django 5.2.16 on 2026-07-18 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_statusevent_work_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_repair', models.PositiveIntegerField(default=1)),
                ('high_risk_threshold', models.PositiveIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'risk scoring configuration',
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('factors', models.JSONField(default=dict)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_assessments', to='equipment.equipment')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
