# Generated by Django 5.2.16 on 2026-07-19 08:31

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('equipment', '0003_alter_equipment_manufacturer_and_more'),
        ('maintenance', '0002_complaint_confirmed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_messages', to='equipment.equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_messages', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assistant_messages', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200)),
                ('model_number', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='manuals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('status_note', models.CharField(blank=True, max_length=300)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manuals_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManualChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField()),
                ('search', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai.servicemanual')),
            ],
        ),
        migrations.AddConstraint(
            model_name='servicemanual',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'model_number'), name='one_manual_per_model'),
        ),
        migrations.AddIndex(
            model_name='manualchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='ai_manualch_search_da3dbf_gin'),
        ),
    ]
